### ISSUE TITLE
Add HTTP with SSL support

### ISSUE THREAD

**Issue by vkottler** [vkottler/runtimepy#251]
https://gist.github.com/zapstar/a7035795483753f7b71a542559afa83f

could test this gist / see how it might integrate into existing `HttpConnection` / `TcpConnection` (ssl config option for TCP factory?)

**Comment by vkottler** [comment]
https://github.com/vkottler/vtelem/blob/master/vtelem/daemon/http.py we had this implementation at one point as well

**Comment by mmbrea** [comment]
Implemented on https://github.com/vkottler/runtimepy/pull/263.
