### ISSUE TITLE
Add slider for minimum frame period to provide client-side performance governor

### ISSUE THREAD

**Issue by mmbrea** [vkottler/runtimepy#264]
i.e. a 240 Hz monitor can bog down the backend due to frame-by-frame messaging. When that kind of update rate is not needed for the task, some mechanism to choose a different frame rate (periods for 30 Hz / 60 Hz / 100 Hz? just a slider?) + supported by URI would probably make the most sense

**Comment by vkottler** [comment]
this is implemented
